osx_image: xcode10.1
language: swift
os: osx
xcode_project: Legere-iOS.xcodeproj
xcode_scheme: Legere-iOS
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone 8

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - pod install --repo-update
script:
  - set -o pipefail
  - xcodebuild -workspace Legere-iOS.xcworkspace -scheme Legere-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c