//
//  AllArticlesInteractor.swift
//  Legere
//
//  Created by Ahmed Ramy on 5/3/19.
//  Copyright (c) 2019 Ahmed Ramy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Promises

final class AllArticlesInteractor: BaseInteractor
{
    init(base: BaseInteractor) {
        super.init(network: base.network, cache: base.cache)
    }
    
    override func process<T>(_ model: T.Type) -> Promise<T> where T : Decodable, T : Encodable {
        return network.callModel(model: model, api: ArticlesService.allArticles)
    }
}
